### ISSUE TITLE
Add support for cmap type 6, 10, 12 fonts

### ISSUE THREAD

**Issue by wind-chh** [pdfminer/pdfminer.six#598]
**Feature request**

Now pdfminer.six only support cmap type 0, 2, 4 which were originally defined prior to Unicode 2.0. New cjk fonts may have other cmap types. This cause a failure on text extraction.

cmap types reference:
https://docs.microsoft.com/en-us/typography/opentype/spec/cmap

I've already added support for cmap type 6, 10, 12 in my own branch. I'll make a PR after adding a test.

**Comment by areqq** [comment]
Could you post a patch ?

**Comment by wind-chh** [comment]
@areqq I pushed the code to https://github.com/wind-chh/pdfminer.six/tree/598-support-cmap-type-6-10-12

Only one file pdffont.py has been modified, you can make a patch with your local version.

**Comment by areqq** [comment]
thanks, unfortunately it doesn't fix my problem with (cid:49)(cid:52)(cid:56)(cid:44)(cid:56) instead of text
 
[wfirma_Faktura_FV_1_2021.pdf](https://github.com/pdfminer/pdfminer.six/files/6377329/wfirma_Faktura_FV_1_2021.pdf)

**Comment by wind-chh** [comment]
seems that there's an encryption on embeded font file in this pdf.

**Comment by areqq** [comment]
may be, but https://pdfbox.apache.org show text without problems

**Comment by wj-Mcat** [comment]
> may be, but https://pdfbox.apache.org show text without problems

what a pity, this is a java libary. Any one can fix `(cid:XX)` error ?

**Comment by wind-chh** [comment]
@areqq @wj-Mcat I think I've fixed this issue. You can try it on branch https://github.com/wind-chh/pdfminer.six/tree/625-support-identity-cmap.

**Comment by wj-Mcat** [comment]
@wind-chh After install with your branch, and test with my local file 
[3.pdf](https://github.com/pdfminer/pdfminer.six/files/6581679/3.pdf)

It can not extract the correct symbol, Did I forget some steps  ?

**Comment by wj-Mcat** [comment]
@wind-chh After After a lot of testing, your solution can significantly reduce the CID problem, but there will still be some parsing errors. Anyway, your solution is a great improvement for us. Thanks a lot.

**Comment by pietermarsman** [comment]
We sill have no support for cmap types above 4, so anyone who can pick this up is welcome to do so.

**Comment by austin-aryn-ai** [comment]
Yes, I can prepare a PR, but it'll be mostly the work done by @wind-chh.  I took his changes and fixed a small bug and made some cosmetic changes.
